/**
 * Postgres adapter for production.
 *   Placeholders  `?` → `$1…$n` (string literals and comments are skipped).
 *   Types         BIGINT and NUMERIC come back as JS numbers. Money is integer milli-Frags, far below 2^53.
 *   Transactions  SERIALIZABLE, retried up to 8 times on 40001/40P01 with jittered backoff, so every
 *                 service keeps the "one transaction at a time" semantics it was written for. A transaction
 *                 must not have effects outside the database before it commits (events go out afterwards).
 *   Migrations    schema_migrations(version); version 1 is the shared schema from db.ts, translated.
 *   Leader        one instance per cluster runs the tickers (crash rounds, PvP settlement, rain, RG scan):
 *                 it holds a session-level advisory lock on a dedicated connection.
 */

import pg from 'pg';

import { type DB, type RunResult, SCHEMA, type Stmt, runAfterCommit } from './db';

pg.types.setTypeParser(20, (v) => Number(v)); // int8
pg.types.setTypeParser(1700, (v) => Number(v)); // numeric

/** Rewrites `?` placeholders to `$n`, leaving string literals, quoted identifiers and comments alone. */
export function toPgSql(sql: string): string {
  let out = '', n = 0;
  for (let i = 0; i < sql.length; i++) {
    const ch = sql[i];
    if (ch === "'" || ch === '"') {
      const end = sql.indexOf(ch, i + 1);
      const j = end === -1 ? sql.length : end;
      out += sql.slice(i, j + 1); i = j; continue;
    }
    if (ch === '-' && sql[i + 1] === '-') {
      const end = sql.indexOf('\n', i);
      const j = end === -1 ? sql.length - 1 : end;
      out += sql.slice(i, j + 1); i = j; continue;
    }
    out += ch === '?' ? `$${++n}` : ch;
  }
  return out;
}

/** Postgres DDL derived from the shared schema. */
export function pgSchema(): string {
  return SCHEMA
    .replace(/INTEGER PRIMARY KEY AUTOINCREMENT/g, 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY')
    .replace(/\bINTEGER\b/g, 'BIGINT')
    .replace(/\bREAL\b/g, 'DOUBLE PRECISION')
    .replace(/CREATE VIEW IF NOT EXISTS/g, 'CREATE OR REPLACE VIEW');
}

const MIGRATIONS: { version: number; sql: () => string }[] = [
  { version: 1, sql: pgSchema },
  // Operator MFA state moved from process memory into the database (needed with several API instances).
  { version: 2, sql: () => `ALTER TABLE users ADD COLUMN IF NOT EXISTS totp_pending TEXT;
    ALTER TABLE users ADD COLUMN IF NOT EXISTS totp_pending_at BIGINT;
    ALTER TABLE sessions ADD COLUMN IF NOT EXISTS mfa_step BIGINT;` },
];

type Queryable = pg.Pool | pg.PoolClient;
const cache = new Map<string, string>();
const text = (sql: string) => { let t = cache.get(sql); if (!t) { t = toPgSql(sql); cache.set(sql, t); } return t; };
const RETRYABLE = new Set(['40001', '40P01']);

export class PgHandle implements DB {
  readonly dialect = 'pg' as const;
  private after: (() => void)[] = [];
  constructor(private q: Queryable, readonly inTx: boolean, readonly pool: pg.Pool) {}
  afterCommit(fn: () => void): void {
    if (this.inTx) this.after.push(fn);
    else runAfterCommit([fn]);
  }
  prepare(sql: string): Stmt {
    const t = text(sql);
    return {
      get: async (...a) => (await this.q.query(t, a)).rows[0],
      all: async (...a) => (await this.q.query(t, a)).rows,
      run: async (...a): Promise<RunResult> => ({ changes: (await this.q.query(t, a)).rowCount ?? 0 }),
    };
  }
  async exec(sql: string): Promise<void> { await this.q.query(sql); }
  async transaction<T>(fn: (db: DB) => Promise<T>): Promise<T> {
    if (this.inTx) return fn(this);
    for (let attempt = 1; ; attempt++) {
      const client = await this.pool.connect();
      try {
        await client.query('BEGIN ISOLATION LEVEL SERIALIZABLE');
        const handle = new PgHandle(client, true, this.pool);
        const out = await fn(handle);
        await client.query('COMMIT');
        runAfterCommit(handle.after);
        return out;
      } catch (e) {
        await client.query('ROLLBACK').catch(() => undefined);
        const code = (e as { code?: string }).code;
        if (code && RETRYABLE.has(code) && attempt < 8) {
          await new Promise((r) => setTimeout(r, Math.random() * 10 * 2 ** attempt));
          continue;
        }
        throw e;
      } finally {
        client.release();
      }
    }
  }
  async close(): Promise<void> { if (!this.inTx) await this.pool.end(); }
}

export interface PgOptions { url: string; max?: number; schema?: string; applicationName?: string }

/** Connects, applies pending migrations and returns the DB handle. `schema` isolates test runs. */
export async function openPg(o: PgOptions): Promise<PgHandle> {
  const pool = new pg.Pool({ connectionString: o.url, max: o.max ?? 10, application_name: o.applicationName ?? 'scrapline',
    options: o.schema ? `-c search_path=${o.schema}` : undefined });
  if (o.schema) {
    if (!/^[a-z_][a-z0-9_]*$/.test(o.schema)) throw new Error('invalid schema name');
    await pool.query(`CREATE SCHEMA IF NOT EXISTS ${o.schema}`);
  }
  await migrate(pool);
  return new PgHandle(pool, false, pool);
}

async function migrate(pool: pg.Pool): Promise<void> {
  const client = await pool.connect();
  try {
    await client.query('SELECT pg_advisory_lock(7261001)'); // one migrator at a time
    await client.query('CREATE TABLE IF NOT EXISTS schema_migrations (version INTEGER PRIMARY KEY, applied_at BIGINT NOT NULL)');
    const done = new Set((await client.query('SELECT version FROM schema_migrations')).rows.map((r) => Number(r.version)));
    for (const m of MIGRATIONS) {
      if (done.has(m.version)) continue;
      await client.query('BEGIN');
      await client.query(m.sql());
      await client.query('INSERT INTO schema_migrations (version, applied_at) VALUES ($1, $2)', [m.version, Date.now()]);
      await client.query('COMMIT');
    }
  } catch (e) {
    await client.query('ROLLBACK').catch(() => undefined);
    throw e;
  } finally {
    await client.query('SELECT pg_advisory_unlock(7261001)').catch(() => undefined);
    client.release();
  }
}

/**
 * Leader election: resolves true once this process holds the tickers lock. The lock lives as long as the
 * dedicated connection; if the leader dies, Postgres drops it and another instance takes over on its next try.
 */
export class PgLeader {
  private client: pg.Client | null = null;
  leader = false;
  constructor(private url: string, private key = 7261002) {}
  async tryAcquire(): Promise<boolean> {
    if (this.leader) return true;
    if (!this.client) {
      this.client = new pg.Client({ connectionString: this.url, application_name: 'scrapline-leader' });
      this.client.on('error', () => { this.leader = false; this.client = null; });
      await this.client.connect();
    }
    this.leader = (await this.client.query('SELECT pg_try_advisory_lock($1) AS ok', [this.key])).rows[0].ok === true;
    return this.leader;
  }
  async release(): Promise<void> { await this.client?.end().catch(() => undefined); this.client = null; this.leader = false; }
}
